"""add trigger_event_id and metadata to notifications

Revision ID: 347d1479409f
Revises: a4a2a2f84047
Create Date: 2026-09-19 16:42:01.108577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '347d1479409f'
down_revision: Union[str, Sequence[str], None] = 'a4a2a2f84047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('trigger_event_id', sa.Uuid(), nullable=True))
    op.add_column('notifications', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('notifications', sa.Column('message', sa.Text(), nullable=True))
    op.add_column('notifications', sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('notifications', sa.Column('failure_reason', sa.Text(), nullable=True))
    op.create_index(op.f('ix_notifications_trigger_event_id'), 'notifications', ['trigger_event_id'], unique=False)
    op.create_unique_constraint('uq_notifications_entry_trigger_type', 'notifications', ['queue_entry_id', 'trigger_event_id', 'notification_type'])
    op.create_foreign_key('fk_notifications_trigger_event_id_queue_events', 'notifications', 'queue_events', ['trigger_event_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_notifications_trigger_event_id_queue_events', 'notifications', type_='foreignkey')
    op.drop_constraint('uq_notifications_entry_trigger_type', 'notifications', type_='unique')
    op.drop_index(op.f('ix_notifications_trigger_event_id'), table_name='notifications')
    op.drop_column('notifications', 'failure_reason')
    op.drop_column('notifications', 'payload_json')
    op.drop_column('notifications', 'message')
    op.drop_column('notifications', 'title')
    op.drop_column('notifications', 'trigger_event_id')
    # ### end Alembic commands ###
