"""create_arrival_plans_and_origin_fields

Revision ID: a4a2a2f84047
Revises: 74bc8c0b08ae
Create Date: 2026-09-19 16:18:08.569593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4a2a2f84047'
down_revision: Union[str, Sequence[str], None] = '74bc8c0b08ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arrival_plans',
    sa.Column('queue_entry_id', sa.Uuid(), nullable=False),
    sa.Column('prediction_snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('travel_provider', sa.String(length=50), nullable=False),
    sa.Column('travel_status', sa.String(length=30), nullable=False),
    sa.Column('travel_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('travel_uncertainty_seconds', sa.Integer(), nullable=True),
    sa.Column('route_distance_meters', sa.Integer(), nullable=True),
    sa.Column('arrival_buffer_seconds', sa.Integer(), nullable=False),
    sa.Column('consultation_start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consultation_end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrival_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrival_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('departure_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('departure_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_meaningful_change', sa.Boolean(), nullable=False),
    sa.Column('consultation_changed', sa.Boolean(), nullable=False),
    sa.Column('travel_changed', sa.Boolean(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['prediction_snapshot_id'], ['prediction_snapshots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['queue_entry_id'], ['queue_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_arrival_plans_entry_created', 'arrival_plans', ['queue_entry_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_arrival_plans_id'), 'arrival_plans', ['id'], unique=False)
    op.create_index('ix_arrival_plans_pred_snap', 'arrival_plans', ['prediction_snapshot_id'], unique=False)
    op.create_index(op.f('ix_arrival_plans_prediction_snapshot_id'), 'arrival_plans', ['prediction_snapshot_id'], unique=False)
    op.create_index(op.f('ix_arrival_plans_queue_entry_id'), 'arrival_plans', ['queue_entry_id'], unique=False)
    op.add_column('queue_entries', sa.Column('origin_latitude', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('queue_entries', sa.Column('origin_longitude', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('queue_entries', sa.Column('travel_mode', sa.String(length=30), server_default='DRIVE', nullable=False))

    op.add_column('queue_entries', sa.Column('travel_origin_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queue_entries', 'travel_origin_updated_at')
    op.drop_column('queue_entries', 'travel_mode')
    op.drop_column('queue_entries', 'origin_longitude')
    op.drop_column('queue_entries', 'origin_latitude')
    op.drop_index(op.f('ix_arrival_plans_queue_entry_id'), table_name='arrival_plans')
    op.drop_index(op.f('ix_arrival_plans_prediction_snapshot_id'), table_name='arrival_plans')
    op.drop_index('ix_arrival_plans_pred_snap', table_name='arrival_plans')
    op.drop_index(op.f('ix_arrival_plans_id'), table_name='arrival_plans')
    op.drop_index('ix_arrival_plans_entry_created', table_name='arrival_plans')
    op.drop_table('arrival_plans')
    # ### end Alembic commands ###
