"""initial_schema

Revision ID: baae6ba8b57e
Revises: 
Create Date: 2026-09-19 14:55:17.537183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'baae6ba8b57e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospitals_id'), 'hospitals', ['id'], unique=False)
    op.create_index(op.f('ix_hospitals_name'), 'hospitals', ['name'], unique=False)
    op.create_table('users',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PATIENT', 'STAFF', 'ADMIN', name='user_role_enum', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('departments',
    sa.Column('hospital_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'name', name='uq_department_hospital_name')
    )
    op.create_index(op.f('ix_departments_hospital_id'), 'departments', ['hospital_id'], unique=False)
    op.create_index('ix_departments_hospital_name', 'departments', ['hospital_id', 'name'], unique=False)
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('doctors',
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'UNAVAILABLE', 'BREAK', name='doctor_status_enum', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctors_department_id'), 'doctors', ['department_id'], unique=False)
    op.create_index(op.f('ix_doctors_id'), 'doctors', ['id'], unique=False)
    op.create_index(op.f('ix_doctors_status'), 'doctors', ['status'], unique=False)
    op.create_table('opd_sessions',
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'ACTIVE', 'PAUSED', 'COMPLETED', 'CANCELLED', name='session_status_enum', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opd_sessions_department_id'), 'opd_sessions', ['department_id'], unique=False)
    op.create_index(op.f('ix_opd_sessions_doctor_id'), 'opd_sessions', ['doctor_id'], unique=False)
    op.create_index('ix_opd_sessions_doctor_starts_at', 'opd_sessions', ['doctor_id', 'starts_at'], unique=False)
    op.create_index(op.f('ix_opd_sessions_id'), 'opd_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_opd_sessions_status'), 'opd_sessions', ['status'], unique=False)
    op.create_table('queues',
    sa.Column('opd_session_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', name='queue_status_enum', native_enum=False), nullable=False),
    sa.Column('current_position', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opd_session_id'], ['opd_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queues_id'), 'queues', ['id'], unique=False)
    op.create_index(op.f('ix_queues_opd_session_id'), 'queues', ['opd_session_id'], unique=False)
    op.create_index(op.f('ix_queues_status'), 'queues', ['status'], unique=False)
    op.create_table('queue_entries',
    sa.Column('queue_id', sa.Uuid(), nullable=False),
    sa.Column('patient_user_id', sa.Uuid(), nullable=False),
    sa.Column('token_number', sa.Integer(), nullable=False),
    sa.Column('priority_class', sa.Enum('NORMAL', 'PRIORITY', 'EMERGENCY', name='priority_class_enum', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'WAITING', 'CALLED', 'IN_CONSULTATION', 'COMPLETED', 'TEMPORARILY_LEFT', 'RETURNED', 'NO_SHOW', name='queue_entry_status_enum', native_enum=False), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('temporary_left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('no_show_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('queue_id', 'token_number', name='uq_queue_token_number')
    )
    op.create_index(op.f('ix_queue_entries_id'), 'queue_entries', ['id'], unique=False)
    op.create_index('ix_queue_entries_patient_created', 'queue_entries', ['patient_user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_queue_entries_patient_user_id'), 'queue_entries', ['patient_user_id'], unique=False)
    op.create_index(op.f('ix_queue_entries_priority_class'), 'queue_entries', ['priority_class'], unique=False)
    op.create_index(op.f('ix_queue_entries_queue_id'), 'queue_entries', ['queue_id'], unique=False)
    op.create_index('ix_queue_entries_queue_status', 'queue_entries', ['queue_id', 'status'], unique=False)
    op.create_index('ix_queue_entries_queue_token', 'queue_entries', ['queue_id', 'token_number'], unique=False)
    op.create_index(op.f('ix_queue_entries_status'), 'queue_entries', ['status'], unique=False)
    op.create_table('consultations',
    sa.Column('queue_entry_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('interruption_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['queue_entry_id'], ['queue_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultations_doctor_id'), 'consultations', ['doctor_id'], unique=False)
    op.create_index('ix_consultations_doctor_started_at', 'consultations', ['doctor_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_consultations_id'), 'consultations', ['id'], unique=False)
    op.create_index('ix_consultations_queue_entry', 'consultations', ['queue_entry_id'], unique=False)
    op.create_index(op.f('ix_consultations_queue_entry_id'), 'consultations', ['queue_entry_id'], unique=True)
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('queue_entry_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('content_reference', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['queue_entry_id'], ['queue_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_queue_entry_id'), 'notifications', ['queue_entry_id'], unique=False)
    op.create_index('ix_notifications_status_created', 'notifications', ['status', 'created_at'], unique=False)
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('queue_events',
    sa.Column('queue_id', sa.Uuid(), nullable=False),
    sa.Column('queue_entry_id', sa.Uuid(), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['queue_entry_id'], ['queue_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queue_events_actor_user_id'), 'queue_events', ['actor_user_id'], unique=False)
    op.create_index('ix_queue_events_entry_time', 'queue_events', ['queue_entry_id', 'event_time'], unique=False)
    op.create_index(op.f('ix_queue_events_event_type'), 'queue_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_queue_events_id'), 'queue_events', ['id'], unique=False)
    op.create_index(op.f('ix_queue_events_queue_entry_id'), 'queue_events', ['queue_entry_id'], unique=False)
    op.create_index(op.f('ix_queue_events_queue_id'), 'queue_events', ['queue_id'], unique=False)
    op.create_index('ix_queue_events_queue_time', 'queue_events', ['queue_id', 'event_time'], unique=False)
    op.create_index('ix_queue_events_type_time', 'queue_events', ['event_type', 'event_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_queue_events_type_time', table_name='queue_events')
    op.drop_index('ix_queue_events_queue_time', table_name='queue_events')
    op.drop_index(op.f('ix_queue_events_queue_id'), table_name='queue_events')
    op.drop_index(op.f('ix_queue_events_queue_entry_id'), table_name='queue_events')
    op.drop_index(op.f('ix_queue_events_id'), table_name='queue_events')
    op.drop_index(op.f('ix_queue_events_event_type'), table_name='queue_events')
    op.drop_index('ix_queue_events_entry_time', table_name='queue_events')
    op.drop_index(op.f('ix_queue_events_actor_user_id'), table_name='queue_events')
    op.drop_table('queue_events')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_index('ix_notifications_status_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_queue_entry_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_consultations_queue_entry_id'), table_name='consultations')
    op.drop_index('ix_consultations_queue_entry', table_name='consultations')
    op.drop_index(op.f('ix_consultations_id'), table_name='consultations')
    op.drop_index('ix_consultations_doctor_started_at', table_name='consultations')
    op.drop_index(op.f('ix_consultations_doctor_id'), table_name='consultations')
    op.drop_table('consultations')
    op.drop_index(op.f('ix_queue_entries_status'), table_name='queue_entries')
    op.drop_index('ix_queue_entries_queue_token', table_name='queue_entries')
    op.drop_index('ix_queue_entries_queue_status', table_name='queue_entries')
    op.drop_index(op.f('ix_queue_entries_queue_id'), table_name='queue_entries')
    op.drop_index(op.f('ix_queue_entries_priority_class'), table_name='queue_entries')
    op.drop_index(op.f('ix_queue_entries_patient_user_id'), table_name='queue_entries')
    op.drop_index('ix_queue_entries_patient_created', table_name='queue_entries')
    op.drop_index(op.f('ix_queue_entries_id'), table_name='queue_entries')
    op.drop_table('queue_entries')
    op.drop_index(op.f('ix_queues_status'), table_name='queues')
    op.drop_index(op.f('ix_queues_opd_session_id'), table_name='queues')
    op.drop_index(op.f('ix_queues_id'), table_name='queues')
    op.drop_table('queues')
    op.drop_index(op.f('ix_opd_sessions_status'), table_name='opd_sessions')
    op.drop_index(op.f('ix_opd_sessions_id'), table_name='opd_sessions')
    op.drop_index('ix_opd_sessions_doctor_starts_at', table_name='opd_sessions')
    op.drop_index(op.f('ix_opd_sessions_doctor_id'), table_name='opd_sessions')
    op.drop_index(op.f('ix_opd_sessions_department_id'), table_name='opd_sessions')
    op.drop_table('opd_sessions')
    op.drop_index(op.f('ix_doctors_status'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_department_id'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_index('ix_departments_hospital_name', table_name='departments')
    op.drop_index(op.f('ix_departments_hospital_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_hospitals_name'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_id'), table_name='hospitals')
    op.drop_table('hospitals')
    # ### end Alembic commands ###
